name: Tests

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"
      - name: Run unit tests
        run: |
          go test -v ./...
